version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: loofah
    versions:
    - 2.9.0
