AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Lint/Debugger:
  AutoCorrect: false
LineLength:
  Max: 120
