AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'node_modules/**/*'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Lint/Debugger:
  AutoCorrect: false
LineLength:
  Max: 120
