version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis:/var/lib/redis/data
  webpack:
    build: .
    command: yarn start
    ports:
      - 3035:3035
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.development
  rails:
    depends_on:
      - postgres
      - redis
      - webpack
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.development
    environment:
      DB_PORT_5432_TCP_ADDR: postgres
      REDIS_URL: redis://redis:6379
  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.development
    environment:
      DB_PORT_5432_TCP_ADDR: postgres
      REDIS_URL: redis://redis:6379
volumes:
  redis:
  postgres:
