
local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'storage') %>

s3:
  service: S3
  access_key_id: <%= ENV.fetch('AWS_S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('AWS_S3_SECRET_ACCESS_KEY') %>
  region: <%= ENV.fetch('AWS_S3_REGION') %>
  bucket: <%= ENV.fetch('AWS_S3_BUCKET') %>
